id: P009658
initial_creation_type: ocr
source_metadata:
  id: bdr:W28887
  title: རྒྱལ་བའི་དབང་པོ་སྐྱབས་རྗེ་ཀརྨ་པ་སྐུ་ཕྲེང་བཅུ་བ་ཆོས་དབྱིངས་རྡོ་རྗེ་མཆོག་གི་གསུང་འབུམ་ལེགས་བཤད་ནོར་བུའི་གཙུག་རྒྱན
  author: ''
  volumes: {}
