id: I80F40D46
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T21:06:28+00:00'
last_modified: '2022-06-08T12:37:35.060785+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28887
  title: རྒྱལ་བའི་དབང་པོ་སྐྱབས་རྗེ་ཀརྨ་པ་སྐུ་ཕྲེང་བཅུ་བ་ཆོས་དབྱིངས་རྡོ་རྗེ་མཆོག་གི་གསུང་འབུམ་ལེགས་བཤད་ནོར་བུའི་གཙུག་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    56AE:
      image_group_id: I4922
      title: ''
      total_pages: 492
      order: 1
      base_file: 56AE.txt
    E419:
      image_group_id: I4923
      title: ''
      total_pages: 480
      order: 2
      base_file: E419.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
